[bookList.tP7cFdLtsPd2du3tcpF8E1]
cover = '/mnt/SLOW_STORAGE/manga/nichijou/cover.jpg'
folder = '/mnt/SLOW_STORAGE/manga/nichijou'
chapterDirs = ['/mnt/SLOW_STORAGE/manga/nichijou/01']

[bookList.qnkf1WzHEzAyJSVGBhMeg8]
cover = '/mnt/SLOW_STORAGE/manga/blue-period/cover.jpg'
folder = '/mnt/SLOW_STORAGE/manga/blue-period'
chapterDirs = ['/mnt/SLOW_STORAGE/manga/blue-period/01']

[bookList.dtEocdWkUuTKCsihYGsqQw]
cover = '/mnt/SLOW_STORAGE/manga/crayon-shin-chan/[臼井儀人] クレヨンしんちゃん 第01巻/Shinchan 1_001.jpg'
folder = '/mnt/SLOW_STORAGE/manga/crayon-shin-chan/[臼井儀人] クレヨンしんちゃん 第01巻'
chapterDirs = ['/mnt/SLOW_STORAGE/manga/crayon-shin-chan/[臼井儀人] クレヨンしんちゃん 第01巻', '/mnt/SLOW_STORAGE/manga/crayon-shin-chan/[臼井儀人] クレヨンしんちゃん 第02巻']

[bubbles.5rPTvyDCbMEhc7dnjGo1pZ]
x = 201.31707763671875
y = 402.2522888183594
filename = '/mnt/SLOW_STORAGE/manga/Uzaki-Chan/Uzaki Chan wa Asobitai  v01/00007.jpg'
id = '5rPTvyDCbMEhc7dnjGo1pZ'
text = 'hello'

[bubbles.bAZ8pNQSh6RoaXVUvRWvwz]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'bAZ8pNQSh6RoaXVUvRWvwz'
text = ''

[bubbles.tBeCKTgkwQqT4aHabKvMCU]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/blue-period/01/00003.jpg'
id = 'tBeCKTgkwQqT4aHabKvMCU'
text = ''

[bubbles.8VyvDV1Qa4tvqYBaHF4Dck]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/blue-period/01/00003.jpg'
id = '8VyvDV1Qa4tvqYBaHF4Dck'
text = ''

[bubbles.dKFSQ3uThe6KbmTDB48ZHP]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/blue-period/01/00003.jpg'
id = 'dKFSQ3uThe6KbmTDB48ZHP'
text = ''

[bubbles.73Aq4E3BVk5g9BpwohmYuP]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/blue-period/01/00003.jpg'
id = '73Aq4E3BVk5g9BpwohmYuP'
text = ''

[bubbles.bCZ7Su4iwRParhcG5VT8qU]
x = 156.1534423828125
y = 330.4266357421875
filename = '/mnt/SLOW_STORAGE/manga/blue-period/01/00003.jpg'
id = 'bCZ7Su4iwRParhcG5VT8qU'
text = 'first bubble'

[bubbles.5xdkWtyBkv23dWVJTwYvet]
x = 100.0
y = 100.0
filename = '/mnt/SLOW_STORAGE/manga/crayon-shin-chan/[臼井儀人] クレヨンしんちゃん 第01巻/Shinchan 1_004.jpg'
id = '5xdkWtyBkv23dWVJTwYvet'
text = 'hello'
