[bookList]

[bubbles.bAZ8pNQSh6RoaXVUvRWvwz]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'bAZ8pNQSh6RoaXVUvRWvwz'
text = ''

[bubbles.dxKpFfuUbbMv6y5Xx6dmLL]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'dxKpFfuUbbMv6y5Xx6dmLL'
text = ''

[bubbles.eQecHEHG6WkNvUP1s68EFG]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'eQecHEHG6WkNvUP1s68EFG'
text = ''

[bubbles.ecYGYXT5dZVkarTyEu7R3u]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'ecYGYXT5dZVkarTyEu7R3u'
text = ''

[bubbles.u9YTswzHcG4vd2NMP54TBp]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'u9YTswzHcG4vd2NMP54TBp'
text = ''

[bubbles.eVrizeBaxZMdVR3wUNDkCD]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'eVrizeBaxZMdVR3wUNDkCD'
text = ''

[bubbles.qfQ8NG2b4tGVrrqyLTk6rt]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/nichijou/01/CMCZIP.CO-005.jpg'
id = 'qfQ8NG2b4tGVrrqyLTk6rt'
text = ''

[bubbles.vxMPk9UQQqZK5Pv9XXKMRv]
x = 250.52587890625
y = 672.4985961914062
filename = '/mnt/SLOW_STORAGE/manga/osama-ranking/01/DLRAW.NET-003.jpg'
id = 'vxMPk9UQQqZK5Pv9XXKMRv'
text = ''

[bubbles.oxByK3EntdLhpDpKkuB9iK]
x = 0.0
y = 0.0
filename = '/mnt/SLOW_STORAGE/manga/osama-ranking/01/DLRAW.NET-003.jpg'
id = 'oxByK3EntdLhpDpKkuB9iK'
text = ''

[bubbles.fmXDX4rEQzRkEyKCy12bJB]
x = 85.240234375
y = 402.7447509765625
filename = '/mnt/SLOW_STORAGE/manga/osama-ranking/01/DLRAW.NET-003.jpg'
id = 'fmXDX4rEQzRkEyKCy12bJB'
text = 'hello'

[bubbles.wFCbbcBWSK7UMR5DWmkfwu]
x = 265.260498046875
y = 262.9483642578125
filename = '/mnt/SLOW_STORAGE/manga/osama-ranking/01/DLRAW.NET-003.jpg'
id = 'wFCbbcBWSK7UMR5DWmkfwu'
text = 'hello'

[bubbles.jVqLUUaCCZZn3x3Ffi9pYC]
x = 45.161376953125
y = 221.34072875976562
filename = '/mnt/SLOW_STORAGE/manga/osama-ranking/01/DLRAW.NET-003.jpg'
id = 'jVqLUUaCCZZn3x3Ffi9pYC'
text = 'hi'
